services:
  agent:
    image: grafana/agent:latest
    volumes:
      - ./otel/agent/agent.river:/etc/agent.river
    command: ["run", "/etc/agent.river"]
    environment:
      - AGENT_MODE=flow
    ports:
      - "4318:4318"  # OTLP HTTP
    depends_on:
      - mimir
      - tempo
      - loki
  mimir:
    image: grafana/mimir:latest
    volumes:
      - ./otel/mimir/config:/etc/mimir-config
    entrypoint:
      - /bin/mimir
      - -config.file=/etc/mimir-config/mimir.yaml
    ports:
      - "9009:9009"
  tempo:
    image: grafana/tempo:2.9.0
    restart: unless-stopped
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./otel/tempo/tempo.yml:/etc/tempo.yaml
    ports:
      - "127.0.0.1:3200:3200"
      - "4317:4317"
      - "7946:7946"

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "127.0.0.1:3100:3100"

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    env_file:
      - ./otel/grafana/.env
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./otel/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - mimir
      - tempo
      - loki

volumes:
  grafana-storage:
