version: "3.8"

services:
  agent:
    image: grafana/agent:latest
    volumes:
      - ./agent/agent.yml:/etc/agent-config.yaml
    command: ["run", "--config.file=/etc/agent-config.yaml"]
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    depends_on:
      - prometheus
      - tempo
      - loki

  prometheus:
    image: prom/prometheus
    volumes:
      - ./otel/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./otel/tempo/tempo.yml:/etc/tempo.yaml

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
      - tempo
      - loki

volumes:
  grafana-storage: