server {
  listen 443 ssl;
  listen [::]:443 ssl;

  server_name aurora.boldman.net;

  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
          ssl_prefer_server_ciphers on;
  ssl_certificate /root/tc.boldman.net/ssl.crt;
  ssl_certificate_key     /root/tc.boldman.net/ssl.key;

  index index.html;

  root "/var/www/html/aurora";
}
