auth_enabled: false

server:
  http_listen_port: 3200
  grpc_listen_port: 4317

receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo
