auth_enabled: false

server:
  http_listen_port: 3200
  grpc_listen_port: 9095

memberlist:
  bind_addr:
    - 0.0.0.0
  bind_port: 7946

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
  ring:
    kvstore:
      store: memberlist

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo

metrics_generator:
  processor:
    span_metrics:
      dimensions: [http.method, http.status_code]
    service_graphs:
      dimensions: [http.method, http.status_code]
  ring:
    kvstore:
      store: memberlist
  storage:
    path: /var/tempo/generator
    remote_write:
      - url: http://mimir:9009/api/v1/push
        send_exemplars: true

overrides:
  defaults:
    metrics_generator:
      processors: [span-metrics, service-graphs]
