server:
  log_level: info
  http_listen_port: 4318

metrics:
  wal_directory: /tmp/grafana-agent-wal
  global:
    scrape_interval: 60s

  configs:
    - name: from_app
      remote_write:
        - url: http://prometheus:9090/api/v1/write
      scrape_configs: []  # No scraping needed

logs:
  configs:
    - name: from_app
      positions:
        filename: /tmp/positions.yaml
      clients:
        - url: http://loki:3100/loki/api/v1/push

traces:
  configs:
    - name: from_app
      remote_write:
        - endpoint: tempo:4317
          insecure: true
