upstream mb {
    server 127.0.0.1:8070;
}

upstream front {
    server 127.0.0.1:3000;
}

server {
    listen   80;
    listen   [::]:80;

    server_name addrtrans.wansong.vip;

    return 307 https://$server_name$request_uri;
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;

        root "/home/ws2356/deploy/addtrans/web_front/build";
        index index.html;

        # location / {
        #   proxy_pass http://front/;
        # }

	server_name addrtrans.wansong.vip;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;
        ssl_certificate /root/.acme.sh/wansong.vip_ecc/fullchain.cer;
        ssl_certificate_key     /root/.acme.sh/wansong.vip_ecc/wansong.vip.key;

	location /api/ {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host;
		proxy_pass http://mb/;
	}
}
