
server {
  listen 443 ssl;
  listen [::]:443 ssl;

  server_name static.boldman.net;
  access_log /var/log/nginx/access.log afd;

  # add_header Content-Security-Policy "default-src 'self'; frame-src *; img-src *; font-src *; style-src *";

  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
	  ssl_prefer_server_ciphers on;
  ssl_certificate /root/.acme.sh/boldman.net_ecc/fullchain.cer;
  ssl_certificate_key     /root/.acme.sh/boldman.net_ecc/boldman.net.key;

  index index.html;

  # Could also do ip filtering but that requires the burden of maintaining afd ip data which is dynamic - https://www.microsoft.com/en-us/download/details.aspx?id=56519
  if ($http_x_azure_fdid != "b10287d9-839f-4084-ba29-7e6c5bcd3ae1") {
      return 400;
  }

# Minimal error page config
  error_page 503 /rate_limited.html;

  location = /rate_limited.html {
    internal;
    add_header Content-Type text/plain;
    return 503 "x";
  }

  location = /open_clip_pytorch_model.bin {
    root "/var/www/html";
    limit_req zone=large_file_download nodelay;
    expires 1y;
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  # Everything else => 404
  location / {
    return 404;
  }
}


