server {
  listen 443 ssl;
  listen [::]:443 ssl;

  server_name dl.boldman.net;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;
  ssl_certificate /root/tc.boldman.net/ssl.crt;
  ssl_certificate_key     /root/tc.boldman.net/ssl.key;

  location = /.well-known/apple-app-site-association {
    default_type application/json;
    add_header Content-Type application/json always;
    # add_header Cache-Control "public, max-age=300" always;
    alias /etc/nginx/conf.d/.well-known/apple-app-site-association;
  }

  location = /apple-app-site-association {
    default_type application/json;
    add_header Content-Type application/json always;
    # add_header Cache-Control "public, max-age=300" always;
    alias /etc/nginx/conf.d/.well-known/apple-app-site-association;
  }

  location = /share {
      return 301 /share/$is_args$args;
  }

  location /share/ {
    alias /var/www/html/instant-share/;

    try_files $uri $uri/ /instant-share/index.html;
  }

  location = /instant-share/index.html {
      alias /var/www/html/instant-share/index.html;
  }

  location /share/assets/ {
    alias /var/www/html/instant-share/assets/;

    expires 1y;
  }

  location /relay {
      proxy_pass http://127.0.0.1:8787;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_read_timeout 300s;
  }

  location / {
    return 301 https://aurora.boldman.net$request_uri;
  }
}
