
server {
  listen 443 ssl;
  listen [::]:443 ssl;

  server_name f.boldman.net;

  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
  ssl_prefer_server_ciphers on;
  ssl_certificate /root/tc.boldman.net/ssl.crt;
  ssl_certificate_key     /root/tc.boldman.net/ssl.key;

  location /2 {
    # 默认值（如果都没匹配上，可以去一个通用页面）
    set $os_platform "default";

    # 判断 Windows
    if ($http_user_agent ~* "windows") {
        return 302 https://apps.microsoft.com/detail/9n5n8gvnrzdn;
    }

    # 判断 macOS
    if ($http_user_agent ~* "macintosh|mac os x") {
        return 302 https://apps.microsoft.com/detail/9n5n8gvnrzdn?os=macos;
    }

    # 判断 Linux
    if ($http_user_agent ~* "linux") {
        return 302 https://apps.microsoft.com/detail/9n5n8gvnrzdn?os=linux;
    }

    # 如果以上都没命中，则执行默认逻辑
    return 302 https://www.baidu.com;
}

  # Everything else => 404
  location / {
    return 404;
  }
}


