server {
  listen 443 ssl;
  listen [::]:443 ssl;

  server_name imagesearch.boldman.net;

  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
          ssl_prefer_server_ciphers on;
  ssl_certificate /root/tc.boldman.net/ssl.crt;
  ssl_certificate_key     /root/tc.boldman.net/ssl.key;

  index index.html;

  location = /open_clip_pytorch_model.bin {
    root "/var/www/html";
    limit_req zone=large_file_download nodelay;
    expires 1y;
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  location = /models/v2.zip {
    root "/var/www/html";
    limit_req zone=large_file_download nodelay;
    expires 1y;
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  root "/var/www/html";
}
