server {
    listen 80 ;
    listen [::]:80;

    server_name mb.wansong.vip;

    # Redirect all HTTP requests to HTTPS with a 301 Moved Permanently response.
    # return 301 https://$host$request_uri;

    index index.html;

    root "/var/www/html";
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;

  server_name mb.wansong.vip;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
	  ssl_prefer_server_ciphers on;
  ssl_certificate /root/.acme.sh/wansong.vip_ecc/fullchain.cer;
  ssl_certificate_key     /root/.acme.sh/wansong.vip_ecc/wansong.vip.key;

  index index.html;

  root "/var/www/html";
}
