upstream otelcollector {
    server 127.0.0.1:4318;
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;

  server_name otel.boldman.net;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
    ssl_prefer_server_ciphers on;
  ssl_certificate /root/.acme.sh/boldman.net_ecc/fullchain.cer;
  ssl_certificate_key     /root/.acme.sh/boldman.net_ecc/boldman.net.key;


# Minimal error page config
  error_page 503 /rate_limited.html;

  location = /rate_limited.html {
    internal;
    add_header Content-Type text/plain;
    return 503 "x";
  }

  location / {
    limit_req zone=rest_api burst=20 nodelay;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $host;
    proxy_pass http://otelcollector/;
  }
}
