upstream pi {
    server 127.0.0.1:2210 fail_timeout=5s max_fails=1;
    server 127.0.0.1:2211 fail_timeout=5s max_fails=1;
    server 127.0.0.1:2212 fail_timeout=5s max_fails=1;
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;

	#ssl_client_certificate certificates/trusted_ca_list.pem;
	#ssl_verify_client on;
	#ssl_crl     crl.pem;
	server_name ~^(pi|picam|ariang|amule).wansong.vip$;

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;
	ssl_certificate /root/.acme.sh/wansong.vip_ecc/fullchain.cer;
	ssl_certificate_key     /root/.acme.sh/wansong.vip_ecc/wansong.vip.key;


	include sso.mixin;

	location / {
                proxy_pass_header X-Transmission-Session-Id;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Host $host;
		proxy_pass http://pi/;
	}
}
