
server {
  listen 443 ssl;
  listen [::]:443 ssl;

  server_name www.wanq.net;

  # add_header Content-Security-Policy "default-src 'self'; frame-src *; img-src *; font-src *; style-src *";

  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
	  ssl_prefer_server_ciphers on;
  ssl_certificate /root/.acme.sh/wanq.net_ecc/fullchain.cer;
  ssl_certificate_key     /root/.acme.sh/wanq.net_ecc/wanq.net.key;

  index index.html;

  root "/var/www/html";
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;

  server_name w3.wansong.vip;

  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
	  ssl_prefer_server_ciphers on;
  ssl_certificate /root/.acme.sh/wansong.vip_ecc/fullchain.cer;
  ssl_certificate_key     /root/.acme.sh/wansong.vip_ecc/wansong.vip.key;

  index index.html;

  root "/var/www/html";
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;

  server_name oneinv.wansong.vip;

  # add_header Content-Security-Policy "default-src 'self'; frame-src *; img-src *; font-src *; style-src *";

  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
	  ssl_prefer_server_ciphers on;
  ssl_certificate /root/.acme.sh/wansong.vip_ecc/fullchain.cer;
  ssl_certificate_key     /root/.acme.sh/wansong.vip_ecc/wansong.vip.key;

  index index.html;

  root "/var/www/html/oneinv";
}


server {
  listen 443 ssl;
  listen [::]:443 ssl;

  server_name authpro.wansong.vip;

  # add_header Content-Security-Policy "default-src 'self'; frame-src *; img-src *; font-src *; style-src *";

  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
  ssl_prefer_server_ciphers on;
  ssl_certificate /root/.acme.sh/wansong.vip_ecc/fullchain.cer;
  ssl_certificate_key     /root/.acme.sh/wansong.vip_ecc/wansong.vip.key;

  index index.html;

  root "/home/ws2356/resume";
}

