map $http_upgrade $ytdl_connection_upgrade {
	default Upgrade;
	''      close;
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;

	# root "/var/www/html/ytdl";

	server_name ytdl.wansong.vip;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;
	ssl_certificate /root/.acme.sh/wansong.vip_ecc/fullchain.cer;
	ssl_certificate_key     /root/.acme.sh/wansong.vip_ecc/wansong.vip.key;

	include sso.mixin;

	location / {
		proxy_pass http://127.0.0.1:8000;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $ytdl_connection_upgrade;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}
