TELEMETRY_UPLOAD_HOST = "https://otel.boldman.net"
METRICS_UPLOAD_ENDPOINT = f"{TELEMETRY_UPLOAD_HOST}/v1/metrics"
TRACES_UPLOAD_ENDPOINT = f"{TELEMETRY_UPLOAD_HOST}/v1/traces"
LOGS_UPLOAD_ENDPOINT = f"{TELEMETRY_UPLOAD_HOST}/v1/logs"
EXPORT_TIMEOUT_SECONDS = 60
EXPORT_BATCH_SIZE = 128 * 1024
EXPORT_QUEUE_SIZE = 1024 * 1024